version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  order-service:
    build: ./order-service
    image: order-service:last
    container_name: order-service
    ports:
      - 8380:8380
    depends_on:
      - postgres

  warehouse-service:
    build: ./warehouse-service
    image: warehouse-service:last
    container_name: warehouse-service
    ports:
      - 8280:8280
    depends_on:
      - postgres

  warranty-service:
    build: ./warranty-service
    image: warranty-service:last
    container_name: warranty-service
    ports:
      - 8180:8180
    depends_on:
      - postgres

volumes:
  db-data:
