name: Build project
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Deploy Warranty Service
        uses: AkhileshNS/heroku-deploy@v3.5.6
        with:
          heroku_api_key: 87d4ce2e-ef40-4f3f-8f36-1d0981ae8759
          heroku_app_name: "mamutova-warranty-service"
          heroku_email: "vlada.mamutova@gmail.com"
          usedocker: true
          appdir: warranty-service
        
      - name: Deploy Warehouse Service
        uses: AkhileshNS/heroku-deploy@v3.5.6
        with:
          heroku_api_key: 87d4ce2e-ef40-4f3f-8f36-1d0981ae8759
          heroku_app_name: "mamutova-warehouse-service"
          heroku_email: "vlada.mamutova@gmail.com"
          usedocker: true
          appdir: warehouse-service
      
      - name: Deploy Order Service
        uses: AkhileshNS/heroku-deploy@v3.5.6
        with:
          heroku_api_key: 87d4ce2e-ef40-4f3f-8f36-1d0981ae8759
          heroku_app_name: "mamutova-order-service"
          heroku_email: "vlada.mamutova@gmail.com"
          usedocker: true
          appdir: order-service
      
      - name: Deploy Store Service
        uses: AkhileshNS/heroku-deploy@v3.5.6
        with:
          heroku_api_key: 87d4ce2e-ef40-4f3f-8f36-1d0981ae8759
          heroku_app_name: "mamutova-store-service"
          heroku_email: "vlada.mamutova@gmail.com"
          usedocker: true
          appdir: store-service
     
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
